#!/bin/bash
[ -z "$ENV_FILES" ] && ENV_FILES="
./traceroute-crawl.conf
/etc/traceroute-crawl/traceroute-crawl.conf
"
for f in $ENV_FILES
do
	if [ -f "$f" ]; then
		set -o allexport
		source "$f"
		set +o allexport
		exec $(dirname ${BASH_SOURCE[0]})/traceroute-crawl.sh $@
	fi
done

echo "No config found" >&2
exit 1
